export const GET_CONTESTS = 'GET_CONTESTS';
export const GET_WALLET_DETAILS = 'GET_WALLET_DETAILS';
export const GET_LANDING_PAGE_DETAILS = 'GET_LANDING_PAGE_DETAILS';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';